### ISSUE TITLE
redux bootstrap example fails with undefined action

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/react-frontend-server-stack#4]

**Comment by bsurai** [comment]
Hi. I've seen "@vscode/..." and "@reduxstack/...". What they are meaning? What is difference between them? What settings do i need to use them?

**Comment by veeramarni** [comment]
@bsurai fixing it and will update the code shortly.

**Comment by bsurai** [comment]
@veeramarni about "@vscode/..." and "@reduxstack/...". I know it's npm scope. "@reduxstack/..." looks like this project. But i can't find any "@vscode" in files, except once in server.ts.

**Comment by veeramarni** [comment]
@bsurai try lerna-move branch now.

**Comment by bsurai** [comment]
@veeramarni  "[ts] Cannot find module '@vscode/redux-bootstrap' "  in "packages\redux-bootstrap-example\server.ts"
